import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        {ambilight}
      </body>
    </html>
  );
}

let ambilight = (
  <svg width="0" height="0">
    <filter
      id="ambilight"
      width="300%"
      height="300%"
      x="-0.75"
      y="-0.75"
      colorInterpolationFilters="sRGB"
    >
      <feOffset in="SourceGraphic" result="source-copy"></feOffset>
      <feColorMatrix
        in="source-copy"
        type="saturate"
        values="3"
        result="saturated-copy"
      ></feColorMatrix>
      <feColorMatrix
        in="saturated-copy"
        type="matrix"
        values="1 0 0 0 0
                     0 1 0 0 0
                     0 0 1 0 0
                     33 33 33 101 -132"
        result="bright-colors"
      ></feColorMatrix>
      <feMorphology
        in="bright-colors"
        operator="dilate"
        radius="10"
        result="spread"
      ></feMorphology>
      <feGaussianBlur
        in="spread"
        stdDeviation="30"
        result="ambilight-light"
      ></feGaussianBlur>
      <feOffset in="SourceGraphic" result="source"></feOffset>
      <feComposite
        in="source"
        in2="ambilight-light"
        operator="over"
      ></feComposite>
    </filter>
  </svg>
);
